### ISSUE TITLE
Database creation

### ISSUE THREAD

**Issue by arobinson56** [vcaldas/iSBatch_old#25]
iSbatch does not create a new database.
Loading is possible.

 
java.lang.NullPointerException
	at model.Importer.<init>(Importer.java:68)
	at operations.AddNodeOperation.<init>(AddNodeOperation.java:52)
	at iSBatch.ISBatch.getTreeOperations(ISBatch.java:556)
	at iSBatch.ISBatch.createTreePanel(ISBatch.java:432)
	at iSBatch.ISBatch.<init>(ISBatch.java:164)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at java.lang.Class.newInstance0(Class.java:357)
	at java.lang.Class.newInstance(Class.java:310)
	at ij.IJ.runUserPlugIn(IJ.java:197)

**Comment by cmpunter** [comment]
You can try to save a new database in an other folder. It might be that Java is not allowed to write to the home folder. There should be an appropriate error message when the program cannot create the database.

**Comment by vcaldas** [comment]
Issue resolved. Database creation is hard coded now.

**Comment by cmpunter** [comment]
@vcaldas Is this already fixed? In the Database class I found the following code:
```java
private void createTablesFromFile() throws SqlJetException {

	database.getOptions().setAutovacuum(true);
	database.beginTransaction(SqlJetTransactionMode.WRITE);
	database.getOptions().setUserVersion(1);
	File test = new File("src//model//template");
```

**This will not work since ```new File("src//model//template");``` will fail once everything is inside a jar file!**

**Comment by vcaldas** [comment]
This is fixed
